os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "6.9.2"
jdk:
    - oraclejdk8
cache:
    yarn: true
    directories:
        - $HOME/.m2
        - $HOME/.gradle
        - $HOME/.yarn-cache
        - $HOME/app/node
env:
    global:
        - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
        - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
        - JHIPSTER_SAMPLES=$TRAVIS_BUILD_DIR/app
        - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
before_install:
    - export TZ=Australia/Canberra
    - date
    - sudo /etc/init.d/mysql stop
    - sudo /etc/init.d/postgresql stop
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # Repo for Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn global add yo bower gulp-cli
    - . $TRAVIS_BUILD_DIR/app/config.sh
install:
    - $JHIPSTER_INSTALL/01-install-jhipster-stack.sh
    - $JHIPSTER_INSTALL/02-checkVersion.sh
    - $JHIPSTER_INSTALL/03-copy-project.sh
script:
    - $TRAVIS_BUILD_DIR/app/test.sh
