os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "4.6.0"
jdk:
    - oraclejdk8
cache:
    directories:
        - node_modules
        - $HOME/.m2
        - $HOME/.gradle
        - $HOME/app/node_modules
        - $HOME/app/node
env:
    global:
        - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
        - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
        - JHIPSTER_SAMPLES=$TRAVIS_BUILD_DIR/app
        - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
before_install:
    - . $TRAVIS_BUILD_DIR/app/config.sh
    - sudo /etc/init.d/postgresql stop
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - $JHIPSTER_INSTALL/02-install-jhipster-stack.sh
    # - $JHIPSTER_INSTALL/03-checkVersion.sh
    # - $JHIPSTER_INSTALL/04-cache.sh
script:
    - echo $JHIPSTER_REPO
    - echo $JHIPSTER_BRANCH
    - echo $JHIPSTER_NODE_CACHE
    - echo $PROFILE
    - echo $RUN_APP
    - echo $PROTRACTOR
    # - $JHIPSTER_SCRIPTS/01-generate-project.sh
    # - $JHIPSTER_SCRIPTS/02-generate-entities.sh
    # - $JHIPSTER_SCRIPTS/03-docker-compose.sh
    # - $JHIPSTER_SCRIPTS/04-tests.sh
    # - $JHIPSTER_SCRIPTS/05-run.sh
    # - $JHIPSTER_SCRIPTS/06-sonar.sh
