os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "6.9.1"
jdk:
    - oraclejdk8
cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
        - $HOME/.yarn
        - $HOME/.yarn-cache
        - $HOME/.yarn-config
        - $HOME/app/node
env:
    global:
        - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
        - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
        - JHIPSTER_SAMPLES=$TRAVIS_BUILD_DIR/app
        - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
before_install:
    - . $TRAVIS_BUILD_DIR/app/config.sh
    - sudo /etc/init.d/postgresql stop
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - $JHIPSTER_INSTALL/02-install-jhipster-stack.sh
    - $JHIPSTER_INSTALL/03-checkVersion.sh
    - $JHIPSTER_INSTALL/04-cache.sh
    - $JHIPSTER_INSTALL/05-copy-project.sh
script:
    - $TRAVIS_BUILD_DIR/app/test.sh
